drop table boarding if exists
drop table boarding if exists
drop table boarding_order if exists
drop table boarding_order_item if exists
drop table credential if exists
drop table customer if exists
drop table customer_order if exists
drop table customer_order_item if exists
drop table emergency_contact if exists
drop table employee if exists
drop table inventory if exists
drop table invoice if exists
drop table invoice_item if exists
drop table note if exists
drop table owner_mapping if exists
drop table pet if exists
drop table web_session if exists
drop sequence if exists hibernate_sequence
create sequence hibernate_sequence start with 1 increment by 1
create table boarding (id bigint generated by default as identity, active boolean, anticipated_drop_off_date date, anticipated_pick_up_date date, created_date date, customer_id bigint, drop_off_date date, invoice_id bigint, pet_id bigint, pet_name varchar(255), pick_up_date date, updated_by_employee_id bigint, updated_date date, primary key (id))
create table boarding_order (id bigint generated by default as identity, active boolean, boarding_id bigint, created_date date, updated_by_employee_id bigint, updated_date date, primary key (id))
create table boarding_order_item (id bigint generated by default as identity, active boolean, boarding_order_id bigint, created_date date, inventory_id bigint, updated_by_employee_id bigint, updated_date date, primary key (id))
create table credential (id bigint generated by default as identity, active boolean, created_date date, password varchar(255), updated_by_employee_id bigint, updated_date date, username varchar(255), primary key (id))
create table customer (id bigint generated by default as identity, active boolean, city varchar(255), created_date date, email varchar(255), first_name varchar(255), last_name varchar(255), middle_name varchar(255), phone varchar(255), state varchar(255), street varchar(255), updated_by_employee_id bigint, updated_date date, zip_code varchar(255), primary key (id))
create table customer_order (id bigint generated by default as identity, active boolean, created_date date, customer_id bigint, customer_name varchar(255), invoice_id bigint, updated_by_employee_id bigint, updated_date date, primary key (id))
create table customer_order_item (id bigint generated by default as identity, active boolean, created_date date, customer_order_id bigint, inventory_id bigint, updated_by_employee_id bigint, updated_date date, primary key (id))
create table emergency_contact (dtype varchar(31) not null, id bigint generated by default as identity, active boolean, created_date date, first_name varchar(255), last_name varchar(255), note varchar(255), phone varchar(255), relation varchar(255), sequence integer, updated_by_employee_id bigint, updated_date date, employee_id bigint, pet_id bigint, primary key (id))
create table employee (id bigint generated by default as identity, active boolean, city varchar(255), created_date date, email varchar(255), first_name varchar(255), last_name varchar(255), middle_name varchar(255), phone varchar(255), role varchar(255), state varchar(255), street varchar(255), title varchar(255), updated_by_employee_id bigint, updated_date date, username varchar(255), zip_code varchar(255), primary key (id))
create table inventory (id bigint generated by default as identity, active boolean, created_date date, name varchar(255), note varchar(255), quantity integer, resale_value decimal(19,2), retail_value decimal(19,2), tax_rate decimal(19,2), taxable boolean, updated_by_employee_id bigint, updated_date date, primary key (id))
create table invoice (id bigint generated by default as identity, active boolean, created_date date, customer_id bigint, customer_name varchar(255), paid boolean, sub_total decimal(19,2), taxes decimal(19,2), total decimal(19,2), updated_by_employee_id bigint, updated_date date, primary key (id))
create table invoice_item (id bigint generated by default as identity, active boolean, date date, invoice_id bigint, name varchar(255), note varchar(255), price decimal(19,2), quantity integer, sub_total decimal(19,2), tax_rate decimal(19,2), taxable boolean, taxes decimal(19,2), total decimal(19,2), primary key (id))
create table note (dtype varchar(31) not null, id bigint generated by default as identity, active boolean, created_date date, note varchar(255), updated_by_employee_id bigint, updated_date date, employee_id bigint, customer_id bigint, boarding_id bigint, pet_id bigint, primary key (id))
create table owner_mapping (id bigint not null, active boolean, created_date date, customer_id bigint, pet_id bigint, updated_by_employee_id bigint, updated_date date, primary key (id))
create table pet (id bigint generated by default as identity, active boolean, age integer, birthday boolean, boarded boolean, breed varchar(255), created_date date, date_of_birth date, first_name varchar(255), last_name varchar(255), middle_name varchar(255), primary_color varchar(255), secondary_color varchar(255), sex varchar(255), type varchar(255), updated_by_employee_id bigint, updated_date date, primary key (id))
create table web_session (id bigint generated by default as identity, active boolean, created_date date, employee_id bigint, end_date date, token varchar(255), primary key (id))
alter table boarding add constraint UK_inqt18o871gr0mbwbw7cpm9rc unique (invoice_id)
alter table credential add constraint UK_cy9bwr22tkmr9hl2iecjqcwvg unique (username)
alter table employee add constraint UK_im8flsuftl52etbhgnr62d6wh unique (username)
alter table inventory add constraint UK_ne303by1rwopd2swtivu9h3kd unique (name)